// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMYhLAVe22Bmt7SzEMrnu8hA5ogWRsADU',
    appId: '1:246367509899:web:4fdfed8e40cff1ca1b638e',
    messagingSenderId: '246367509899',
    projectId: 'dsi-2021-2',
    authDomain: 'dsi-2021-2.firebaseapp.com',
    storageBucket: 'dsi-2021-2.appspot.com',
    measurementId: 'G-7PT6P2FS50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF-asP-CJzbzaHs5Dx4KTUJf7uoBzdBpc',
    appId: '1:246367509899:android:b8177bd84c185a0b1b638e',
    messagingSenderId: '246367509899',
    projectId: 'dsi-2021-2',
    storageBucket: 'dsi-2021-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjG_DSEc9M3TwkrACuKftznrWolGpvAtE',
    appId: '1:246367509899:ios:4fa2d773dd16e2ca1b638e',
    messagingSenderId: '246367509899',
    projectId: 'dsi-2021-2',
    storageBucket: 'dsi-2021-2.appspot.com',
    iosClientId: '246367509899-11r7epb7deq461jke5v5m2soc8r7crgu.apps.googleusercontent.com',
    iosBundleId: 'com.example.randomizador',
  );
}
